version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            
        working_dir: /app

        volumes:
            - .:/app
        command: flask run --host=0.0.0.0
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=development
        expose:
            - "5000"

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web